name: Executar Testes

on: [push, pull_request]

jobs:
  -runs-on: ubuntu-lastest

  steps:
    - name: Clonar Repositório
    - uses: actions/checkout@v4

    - name: Instalar .Net
    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '9.0.x'

    - name: Restaurar Dependências
      run: dotnet restore

    - name: Executar Testes
      run: dotnet test --logger "trx;LogFileName=resultado.trx"

    - name: Salvar relatório
      uses: actions/upload=artifact@v4
      with:
        name: resultados-Testes
        path: **/resultados.trx
