name: Executar Testes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v4

      - name: Instalar .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Restaurar Dependências
        run: dotnet restore ScreenSound.sln
        working-directory: ScreenSound

      - name: Executar Testes
        run: dotnet test ScreenSound.sln --logger "trx;LogFileName=resultado.trx" --filter Categoria=Integração
        working-directory: ScreenSound

      - name: Salvar relatório
        uses: actions/upload-artifact@v4
        with:
          name: resultados-testes
          path: resultado.trx