name: Executar Testes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v4

      - name: Instalar .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Restaurar Dependências
        run: dotnet restore ScreenSound.sln
        working-directory: ScreenSound

      - name: Executar Testes
        run: dotnet test ScreenSound.sln --logger "trx;LogFileName=resultado.trx" --filter Categoria=Integração
        working-directory: ScreenSound

      - name: Salvar relatório
        uses: actions/upload-artifact@v4
        with:
          name: resultados-testes
          path: resultado.trx

      - name: Executar testes e gerar cobertura
        run: dotnet test ScreenSound.sln --collect:"XPlat Code Coverage" --filter Categoria=Integração
        working-directory: ScreenSound

      - name: Localizar arquivo de cobertura
        id: cobertura
        shell: pwsh
        run: |
          $file = Get-ChildItem -Path "ScreenSound.Tests.Integracao/TestResults" -Recurse -Filter "coverage.cobertura.xml" | Select-Object -First 1
          echo "coverage_file=$($file.FullName)" >> $env:GITHUB_ENV
        working-directory: ScreenSound

      - name: Instalar ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Gerar relatório de cobertura
        run: |
          reportgenerator -reports:"${{ env.coverage_file }}" -targetdir:"ScreenSound.Tests.Integracao/RelatorioCobertura" -reporttypes:Html
        working-directory: ScreenSound

      - name: Listar arquivos do relatório
        run: Get-ChildItem -Path "ScreenSound.Tests.Integracao/RelatorioCobertura" -Recurse
        shell: pwsh
        working-directory: ScreenSound

      - name: Upload do artefato do relatório de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: ScreenSound.Tests.Integracao/RelatorioCobertura